apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: consignment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consignment
  template:
    metadata:
      labels:
        app: consignment
    spec:
      containers:
      - name: consignment-service
      # below line should be docker image
        image: eu.gcr.io/blink/consignment-service:latest
        imagePullPolicy: Always
        command: [
          "./shippy-consignment-service",
          "--selector=static",
          "--server_address=:8080",
        ]
        env:
          - name: DB_HOST
            value: "mongo:27017"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
          name: consignment-port
