apiVersion: v1
kind: Service
metadata:
  name: micro-gateway
spec:
  type: LoadBalancer
  selector:
    app: micro-gateway
  ports:
  - name: api-gateway
    port: 80
    targetPort: "port"
    protocol: TCP
