apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user-service
      # below line should be docker image
        image: eu.gcr.io/blink/user-service:latest
        imagePullPolicy: Always
        command: [
          "./shippy-user-service",
          "--selector=static",
          "--server_address=:8080",
        ]
        env:
          - name: DB_HOST
            value: "postgres:5432"
          - name: DB_NAME
            value: "postgres"
          - name: DB_PASS
            value: "postgres"
          - name: DB_USER
            value: "postgres"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
          name: user-port
